### PR TITLE
Translation corrected

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@Mte90 @SamMousa @Kallys @frasiek 

Hello?

**Comment by Mte90** [comment]
I am not one of the developer of this project just an user.

**Comment by Justman10000** [comment]
> 
> 
> I am not one of the developer of this project just an user.

Then why were you suggested in the mentions?

**Comment by Mte90** [comment]
Maybe because I opened some tickets too on this repo.
Doesn't show in the autocomplete menu only the maintainers...

**Comment by Justman10000** [comment]
@ivandiazwm @guillegiu 

Hello?

**Comment by SamMousa** [comment]
@Justman10000 randomly pinging people is considered spamming. Please stop it.
You obviously have no idea what you are doing and are randomly pinging people because github autocomplete offers you their handle when you type `@`. 

Maybe visit the opensupport website and use the contact page to get in contact with their team...

**Comment by Justman10000** [comment]
> 
> 
> @Justman10000 randomly pinging people is considered spamming. Please stop it.
> You obviously have no idea what you are doing and are randomly pinging people because github autocomplete offers you their handle when you type `@`.
> 
> Maybe visit the opensupport website and use the contact page to get in contact with their team...

I don't spam, I just wanted to mark the team, but I forgot that @ is not only listing the team! And Github is there to get support, or is the function [Issues](https://github.com/opensupports/opensupports/issues) deco? I just want the issues and pull requests to be processed, that's already piling up!

**Pull request merged**
