### PR TITLE
[DEV-339] Fix DropDown style

### PR DESCRIPTION
**Pull request by LautaroCesso**

### CODE REVIEW

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before:
image

After:
image

**Comment by LautaroCesso** [comment]
Before last commit xd:
image

After last commit:
image

Now:
image

**Review by mredigonda — APPROVED** [review]
LGTM

**Pull request merged**
